### PR TITLE
Added MeanStdDev

### PR DESCRIPTION
**Pull request by fredcarle**
I added MeanStdDev to cxcore.go but did not include testing (not sure how to do it properly).

### CODE REVIEW

**Comment by lazywei** [comment]
If you're asking where to put the test: you could just put the test at cxcore_test.go.
If you're asking what cases to test: I think you can generate some artificial matrix and test if the output is the same as the closed-form mean / std deviation formula.

Thanks.

**Comment by kevinabrandon** [comment]
I'd suggest having the MeanStdDev return the results, instead of using the passed in arguments.

Also I'd change the MeanStdDev to work with an IplImage instead of the Mat.  If you want, you could even make it an IplImage method so it would look something like:

```
func (img *IplImage) MeanStdDev() (Scalar, Scalar) {
  return MeanStdDevWithMask(img, nil)
}

func MeanStdDevWithMask(img, mask *IplImage) (Scalar, Scalar) {
  var mean, stdDev Scalar
  C.cvAvgSdv(
    unsafe.Pointer(img),
    (*C.CvScalar)(&mean),
    (*C.CvScalar)(&stdDev),
    unsafe.Pointer(mask),
  )
  return mean, stdDev
}
```
Then you could do something like this in your main code:

```
img := cap.QueryFrame()
mean, stdDev := img.MeanStdDev()

```

**Comment by fredcarle** [comment]
@lazywei, I'll try to do that.

@kevinabrandon, I like the idea. I'll do the changes right now.

**Comment by fredcarle** [comment]
Let me know if the latest changes are acceptable. I also added my motion detection sample which is still incomplete. I wanted to work on this a lot more in the past month but I started a new job and it's just been too crazy.

**Comment by lazywei** [comment]
Thanks for the effort @fredcarle .

**Pull request merged**
