### PR TITLE
Feature/contours

### PR DESCRIPTION
**Pull request by davidoram**
Added function to support the detection and drawing of contours

### CODE REVIEW

**Comment by lazywei** [comment]
Thanks for the effort.

**Comment by davidoram** [comment]
Wow - so fast
:+1:

**Comment by lazywei** [comment]
:+1: would love to have your contribution in the future!
Thanks.

**Comment by davidoram** [comment]
I just realised that `images/shapes.png` not used. I'll remove in my next PR.

BTW - Just wanted to say well done on this project, I'm finding it very useful

**Pull request merged**
